<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\Exportable;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Events\AfterSheet;
use Maatwebsite\Excel\Events\BeforeExport;

class VendorOfferExport implements FromCollection,
WithHeadings,
WithMapping,
WithEvents,
WithTitle,
ShouldAutoSize
{

    use Exportable;
    private $query;
    private $fileName;

    public function __construct($query, $fileName = null)
    {
        $this->query = $query;
        if (!$fileName) {
            $this->fileName = "vendor_offer_" . date("Y-m-dHis") . ".xlsx";
        } else {
            $this->fileName = $fileName;
        }
    }
    /**
     * @return \Illuminate\Support\FromQuery
     */
    public function collection()
    {
        return $this->query;
    }
    public function headings(): array
    {
        return [
            "Date",
            "confirmation Code",
            "Vendor",
            "Qty",
            "Offer Price",
            "Exp. Fine leaf count",
            "Exp. Moisture",
            "Status",
        ];
    }
    public function map($vendor_offer): array
    {
        return [
            $vendor_offer->created_at->format("Y-m-d"),
            $vendor_offer->confirmation_code ?? "N/A",
            $vendor_offer->vendor->name,
            $vendor_offer->leaf_quantity,
            $vendor_offer->offer_price,
            $vendor_offer->expected_fine_leaf_count,
            $vendor_offer->expected_moisture,
            $vendor_offer->status,
        ];
    }
    /**
     * @return array
     */
    public function registerEvents(): array
    {
        return [
            // Handle by a closure.
            BeforeExport::class => function (BeforeExport $event) {
                $event->writer->getProperties()->setCreator('Web.com Pvt Ltd.')
                ->setLastModifiedBy("Tea Weighment App")
                ->setSubject("Tea Weighment App")
                ->setDescription(
                    "This is document is generated by Online Tea Weighment App."
                )
                ->setKeywords("office Vendor Offers")
                ->setCompany('Web.com Pvt Ltd.')
                ->setManager('Web.com Pvt Ltd.')
                ->setCategory("Vendor Offers");
            },
        ];
    }
    public function title(): string
    {
        return "Tea Weighment App";
    }
}
